const express = require("express");
const router = express.Router();

// Modülleri içe aktarıyoruz
const adminRoutes = require("./adminRoutes");
const councilMemberRoutes = require("./councilMemberRoutes");
const departmentRoutes = require("./departmentRoutes");
const directiveRoutes = require("./directiveRoutes");
const employeeRoutes = require("./employeeRoutes");
const eventRoutes = require("./eventRoutes");
const eventGalleryRoutes = require("./eventGalleryRoutes");
const facilityRoutes = require("./facilityRoutes");
const facilityGalleryRoutes = require("./facilityGalleryRoutes");
const newsRoutes = require("./newsRoutes");
const newsGalleryRoutes = require("./newsGalleryRoutes");
const pressReleaseRoutes = require("./pressReleaseRoutes");
const pressReleaseGalleryRoutes = require("./pressReleaseGalleryRoutes");
const presidentRoutes = require("./presidentRoutes");
const presidentGalleryRoutes = require("./presidentGalleryRoutes");
const pressMaterialRoutes = require("./pressMaterialRoutes");
const publicationRoutes = require("./publicationRoutes");
const activityReportRoutes = require("./activityReportRoutes");
const financialExpectationReportRoutes = require("./financialExpectationReportRoutes");
const performanceProgramRoutes = require("./performanceProgramRoutes");
const auditReportRoutes = require("./auditReportRoutes");
const strategicPlanRoutes = require("./strategicPlanRoutes");
const kvkkDocumentRoutes = require("./kvkkDocumentRoutes");
const departmentDocumentRoutes = require("./departmentDocumentRoutes");
const serviceRoutes = require("./serviceRoutes");
const serviceFormRoutes = require("./serviceFormRoutes");
const suggestionRoutes = require("./suggestionRoutes");
const vicePresidentRoutes = require("./vicePresidentRoutes");
const gatheringAreaRoutes = require("./gatheringAreaRoutes");
const freeWifiPointRoutes = require("./freeWifiPointRoutes");
const wastePointRoutes = require("./wastePointRoutes");
const marketplaceRoutes = require("./marketplaceRoutes");
const editorImageRoutes = require("./editorImageRoutes");
const photoGalleryRoutes = require("./photoGalleryRoutes");
const contentPopupRoutes = require("./contentPopupRoutes");
const institutionHistoryRoutes = require("./institutionHistoryRoutes");
const workplaceLicenseRoutes = require("./workplaceLicenseRoutes");

// Rotaları ana router'a bağlıyoruz
router.use("/admin", adminRoutes);
router.use("/council-members", councilMemberRoutes);
router.use("/departments", departmentRoutes);
router.use("/directives", directiveRoutes);
router.use("/employees", employeeRoutes);
router.use("/events", eventRoutes);
router.use("/event-galleries", eventGalleryRoutes);
router.use("/facilities", facilityRoutes);
router.use("/facility-galleries", facilityGalleryRoutes);
router.use("/news", newsRoutes);
router.use("/news-galleries", newsGalleryRoutes);
router.use("/press-releases", pressReleaseRoutes);
router.use("/press-release-galleries", pressReleaseGalleryRoutes);
router.use("/president", presidentRoutes);
router.use("/president-galleries", presidentGalleryRoutes);
router.use("/press-materials", pressMaterialRoutes);
router.use("/publications", publicationRoutes);
router.use("/activity-reports", activityReportRoutes);
router.use("/financial-expectation-reports", financialExpectationReportRoutes);
router.use("/performance-programs", performanceProgramRoutes);
router.use("/audit-reports", auditReportRoutes);
router.use("/strategic-plans", strategicPlanRoutes);
router.use("/kvkk-documents", kvkkDocumentRoutes);
router.use("/department-documents", departmentDocumentRoutes);
router.use("/services", serviceRoutes);
router.use("/service-forms", serviceFormRoutes);
router.use("/suggestions", suggestionRoutes);
router.use("/vice-presidents", vicePresidentRoutes);
router.use("/gathering-areas", gatheringAreaRoutes);
router.use("/free-wifi-points", freeWifiPointRoutes);
router.use("/waste-points", wastePointRoutes);
router.use("/marketplaces", marketplaceRoutes);
router.use("/editor-images", editorImageRoutes);
router.use("/photo-gallery", photoGalleryRoutes);
router.use("/content-popups", contentPopupRoutes);
router.use("/institution-history", institutionHistoryRoutes);
router.use("/workplace-licenses", workplaceLicenseRoutes);

module.exports = router;
