const express = require("express");
const router = express.Router();

// Modülleri içe aktarıyoruz
const adminRoutes = require("./adminRoutes");
const councilDecisionRoutes = require("./councilDecisionRoutes");
const councilMemberRoutes = require("./councilMemberRoutes");
const departmentRoutes = require("./departmentRoutes");
const directiveRoutes = require("./directiveRoutes");
const employeeRoutes = require("./employeeRoutes");
const encumenRoutes = require("./encumenRoutes");
const encumenMemberRoutes = require("./encumenMemberRoutes");
const eventRoutes = require("./eventRoutes");
const eventGalleryRoutes = require("./eventGalleryRoutes");
const facilityRoutes = require("./facilityRoutes");
const facilityGalleryRoutes = require("./facilityGalleryRoutes");
const newsRoutes = require("./newsRoutes");
const newsGalleryRoutes = require("./newsGalleryRoutes");
const presidentRoutes = require("./presidentRoutes");
const presidentGalleryRoutes = require("./presidentGalleryRoutes");
const pressMaterialRoutes = require("./pressMaterialRoutes");
const publicNoticeRoutes = require("./publicNoticeRoutes");
const activityReportRoutes = require("./activityReportRoutes");
const financialExpectationReportRoutes = require("./financialExpectationReportRoutes");
const performanceProgramRoutes = require("./performanceProgramRoutes");
const auditReportRoutes = require("./auditReportRoutes");
const strategicPlanRoutes = require("./strategicPlanRoutes");
const kvkkDocumentRoutes = require("./kvkkDocumentRoutes");
const serviceRoutes = require("./serviceRoutes");
const serviceFormRoutes = require("./serviceFormRoutes");
const suggestionRoutes = require("./suggestionRoutes");
const tenderRoutes = require("./tenderRoutes");
const vicePresidentRoutes = require("./vicePresidentRoutes");
const realEstateListingRoutes = require("./realEstateListingRoutes");
const gatheringAreaRoutes = require("./gatheringAreaRoutes");
const freeWifiPointRoutes = require("./freeWifiPointRoutes");
const wastePointRoutes = require("./wastePointRoutes");
const marketplaceRoutes = require("./marketplaceRoutes");

// Rotaları ana router'a bağlıyoruz
router.use("/admin", adminRoutes);
router.use("/council-decisions", councilDecisionRoutes);
router.use("/council-members", councilMemberRoutes);
router.use("/departments", departmentRoutes);
router.use("/directives", directiveRoutes);
router.use("/employees", employeeRoutes);
router.use("/encumens", encumenRoutes);
router.use("/encumen-members", encumenMemberRoutes);
router.use("/events", eventRoutes);
router.use("/event-galleries", eventGalleryRoutes);
router.use("/facilities", facilityRoutes);
router.use("/facility-galleries", facilityGalleryRoutes);
router.use("/news", newsRoutes);
router.use("/news-galleries", newsGalleryRoutes);
router.use("/president", presidentRoutes);
router.use("/president-galleries", presidentGalleryRoutes);
router.use("/press-materials", pressMaterialRoutes);
router.use("/public-notices", publicNoticeRoutes);
router.use("/activity-reports", activityReportRoutes);
router.use("/financial-expectation-reports", financialExpectationReportRoutes);
router.use("/performance-programs", performanceProgramRoutes);
router.use("/audit-reports", auditReportRoutes);
router.use("/strategic-plans", strategicPlanRoutes);
router.use("/kvkk-documents", kvkkDocumentRoutes);
router.use("/services", serviceRoutes);
router.use("/service-forms", serviceFormRoutes);
router.use("/suggestions", suggestionRoutes);
router.use("/tenders", tenderRoutes);
router.use("/vice-presidents", vicePresidentRoutes);
router.use("/real-estate-listings", realEstateListingRoutes);
router.use("/gathering-areas", gatheringAreaRoutes);
router.use("/free-wifi-points", freeWifiPointRoutes);
router.use("/waste-points", wastePointRoutes);
router.use("/marketplaces", marketplaceRoutes);

module.exports = router;
